FROM node:14-alpine as reactapp

WORKDIR /app


COPY package.json ./
RUN npm install
COPY . .
RUN npm run build


FROM nginx

COPY --from=reactapp /app/build /usr/share/nginx/html

RUN rm ./etc/nginx/nginx.conf

COPY nginx/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx" ,"-g" ,"daemon off"]