version: "3"
services:
  app: #just put any name
    build:
      context: . #current directory
      dockerfile: Dockerfile.prod #any docker file name  like for Dockerfile.prod
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"

    env_file:
      - ./.env
